### ISSUE TITLE
Remove base64 encoding

### ISSUE THREAD

**Issue by msalvaris** [Microsoft/AKSDeploymentTutorialAML#3]
It is possible now in AML to access the raw request object https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-consume-web-service#request-data

We should replace the string encoding with this

**Comment by fboylu** [comment]
I have seen this as well in a tutorial, definitely needs to be fixed.

**Comment by msalvaris** [comment]
@fboylu Do you have a link? The tutorials in AML repo still use the old way https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training-with-deep-learning/train-hyperparameter-tune-deploy-with-pytorch/pytorch_score.py

**Comment by fboylu** [comment]
Look here at the bottom where they test, there is no base64, did you not mean that?
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training-with-deep-learning/train-hyperparameter-tune-deploy-with-pytorch/train-hyperparameter-tune-deploy-with-pytorch.ipynb

**Comment by msalvaris** [comment]
Thanks @fboylu. Looking at it it does this {'data': input_data.tolist()} which is worse than base64. It is the numpy array values like so [54, 14, 45 ....] which will be huge. The method we are talking about will preserve compression.

**Comment by fboylu** [comment]
I agree, I didn't like .tolist() either but interestingly tensorflow serving does the same... Look here https://www.tensorflow.org/serving/tutorials/Serving_REST_simple, the request part.

**Comment by msalvaris** [comment]
Ha ok, with fashion mnist the overhead is negligable. I wonder what they do for object detection?

**Comment by msalvaris** [comment]
This looks more like the official way to do it https://towardsdatascience.com/how-to-deploy-machine-learning-models-with-tensorflow-part-1-make-your-model-ready-for-serving-776a14ec3198

**Comment by msalvaris** [comment]
Funny Google advocates base64 encoding for their service https://cloud.google.com/vision/automl/docs/base64 :D
