### ISSUE TITLE
Notebook 02 breaks when model_name other than 'resnet_model" provided

### ISSUE THREAD

**Issue by fboylu** [Microsoft/AKSDeploymentTutorialAML#8]
Notebook 00 asks for model_name to be provided by the user however  model_name is hardcoded as "resnet_model" in scoring script so when user provides different model_name, scoring script breaks. Also, unclear why and how _MODEL_NAME  is used in 02.

**Comment by YanZhangADS** [comment]
addressed. removed the input parameter model_name
